import type { Metadata } from "next";
import {poppins} from "@/app/fonts";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased h-screen w-screen bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
